### ISSUE TITLE
Add SCPI command to add COEFFICIENT comment(s)

### ISSUE THREAD

**Issue by bvernoux** [jankae/LibreCAL#10]
It will be great to add SCPI command to add COEFFICIENT header comments especially to provide details of VNA and setup used ...
The SCPI command could be named :COEFF:ADD_COMMENT with parameter containing a string for the comment up to 120 chars maximum for example

**Comment by bvernoux** [comment]
@jankae Are you ok for that proposal ? as I plan to implement it (and do a PR after)

**Comment by jankae** [comment]
Sure, if you think this is a useful addition go ahead and implement it. How to you plan to store the comment on the device?

**Comment by bvernoux** [comment]
I have implemented and tested the :COEFF:ADD_COMMENT
All as been added in https://github.com/jankae/LibreCAL/pull/8
Specific commit related to :COEFF:ADD_COMMENT
- SCPI_API Documentation updated adding SCPI command :COEFFicient:ADD_COMMENT https://github.com/jankae/LibreCAL/pull/8/commits/a22ee132b7a06a0b4fd45fa34b18e5e32ef5b5d3
-  LibreCAL firmware updated (v0.2.0) adding SCPI command :COEFFicient:ADD_COMMENT https://github.com/jankae/LibreCAL/pull/8/commits/b60f97b89543912e5befc02ab9dcee79e583c832
-  Add Python3 Scripts for FactoryCoefficients tests with VNA_Example_Test and createFactoryCoefficients_Test.py to test the LibreCAL Firmware with dummy data and different test cases https://github.com/jankae/LibreCAL/pull/8/commits/d62220ee106fe2a2741c05097bbfb8fcb5c52921

**Comment by bvernoux** [comment]
Feature merged issue closed
