### ISSUE TITLE
LibreCAL USB VID/PID not official

### ISSUE THREAD

**Issue by bvernoux** [jankae/LibreCAL#12]
I have discovered (in https://github.com/jankae/LibreCAL/blob/main/Software/LibreCAL/src/USB/usb_descriptors.c#L50) that LibreCAL use following VID/PID:
- USB VID: 0x0483 corresponding to [STMicroelectronics]
- USB PID: 0x4122 not used officially by ST

I really doubt such USB VID / PID usage are allowed by STMicroelectronics (especially as the LibreCAL does not use any STMicroelectronics MCU) and it will be better to ask for official one from https://github.com/pidcodes/pidcodes.github.com
LibreCAL (like LibreVNA) will comply to all rules of pidcodes to obtain dedicated PID (using their VID 0x1209 ) which requires open source firmware and open source hardware

**Comment by jankae** [comment]
Thanks, I was aware of the pidcodes project but didn't bother with it so far - thanks for pushing the issue. I have just requested a PID for the LibreCAL as well as the LibreVNA

**Comment by bvernoux** [comment]
Great news I see the PR is here https://github.com/pidcodes/pidcodes.github.com/pull/830
Latest status is => All good. Repos are clear.
So soon it shall be merged and official

**Comment by jankae** [comment]
The PR on the pidcodes was merged and I updated the PID/VID for both this and the LibreVNA project. I am having some compiler issues on my end so I am unable to verify the change but I literally just changed the defined VID so I think this is safe to commit without testing
