### ISSUE TITLE
Transparent Emulation mode for common commercial e-Cal

### ISSUE THREAD

**Issue by bvernoux** [jankae/LibreCAL#19]
It will be great to study and implement an emulation mode for following commercial standard E-Cal:
- PicoVNA E-Cal 8.5 GHz Automated calibration kits, 2-Port (even if we are limited to <8GHz Max) 
   - https://www.picotech.com/accessories/cal-and-check-standards/picovna-e-cal
- Keysight N7551A Electronic Calibration Module, DC to 6.5 GHz, 2-Port 
   - https://www.keysight.com/fr/en/product/N7551A/electronic-calibration-module-ecal-dc-6-5-ghz-2-port.html
- Keysight N443x Electronic Calibration Module, DC to 13.5 GHz, 4-Port (even if we are limited to <8GHz Max) 
   - https://www.keysight.com/fr/en/product/N4431D/rf-electronic-calibration-module-ecal-dc-13-5-ghz-4-ports.html
   - https://www.keysight.com/fr/en/product/N4432D/rf-electronic-calibration-module-ecal-dc-300-khz-18-ghz-4-ports.html
   - https://www.keysight.com/fr/en/product/N4433D/rf-electronic-calibration-module-ecal-dc-300khz-26-5ghz-4-ports.html
- Rohde & Schwarz R&S ZN-Z5x automatic calibration units Models up to 50 GHz,  with 2 and 4 ports, configurable ports 
   - https://www.rohde-schwarz.com/us/products/test-and-measurement/electronic-and-inline-calibration-units/rs-zn-z5x-automatic-calibration-units_63493-418496.html
- Other TBD ? (the most used by priority with guys which can test / validate and own the hardware)

The immediate interest will be to fully emulate other e-CAL to replace them transparently with cheaper fully open source / open hardware LibreCAL which can support up to 4-Port e-CAL

**Comment by jankae** [comment]
Hi, thanks for the suggestion. At the moment there are a couple of things that prevent me from even attempting this:

- I couldn't find the required documentation of the protocols used by these e-Cals (I would need a very detailed description of the USB protocol, down to the USB endpoints)
- I don't own any of these or any equipment that supports these e-Cals, so I wouldn't be able to test anything
- The companies might not react kindly to replicating their protocols and essentially pretending to be their e-Cal

So for now, I don't think there is anything that can be done here.
