### ISSUE TITLE
Questions about Manual control use case with Port Select Port1/2/3/4 & Function Select Through

### ISSUE THREAD

**Issue by bvernoux** [jankae/LibreCAL#4]
Today it is not very clear how work the Manual control towards Through Function selection and Port Select Port1/2/3/4 (checked also in latest documentation https://github.com/jankae/LibreCAL/blob/main/Documentation/manual.pdf October 3, 2022)
If I want to do manual calibration all is clear for Port Select of PORT1/2/3/4 and Function Select for Open/Short/Load
But it is not clear for Through especially as Through requires to know Source & Destination Port and it is not clear how we can select that in Manual control.

Could you clarify how it works with Manual control ?
Case Port1 & Through:
- I have Port Select => Port1
- I have Function Select => Through
- Does it imply Through is between Port1 and Port2 ? (I suspect it is default case to be confirmed)
- How does it is displayed with LEDs ? 
  - Does Both Port1 & Port2 LEDs are blinking or fix... to clearly show that the Through will be between those 2 ports ?

Case Port2 & Through:
- I have Port Select => Port2
- I have Function Select => Through
- Does it imply Through is between Port2 and Port1 ? (I suspect it is default case to be confirmed)
- How does it is displayed with LEDs ? 
  - Does Both Port1 & Port2 LEDs are blinking or fix... to clearly show that the Through will be between those 2 ports ?

Case Port3 & Through:
- I have Port Select => Port3
- I have Function Select => Through
- Does it imply Through is between Port3 and Port4 ? (I suspect it is default case to be confirmed)
- How does it is displayed with LEDs ? 
  - Does Both Port3 & Port4 LEDs are blinking or fix... to clearly show that the Through will be between those 2 ports ?

Case Port4 & Through:
- I have Port Select => Port4
- I have Function Select => Through
- Does it imply Through is between Port4 and Port3 ? (I suspect it is default case to be confirmed)
- How does it is displayed with LEDs ? 
  - Does Both Port3 & Port4 LEDs are blinking or fix... to clearly show that the Through will be between those 2 ports ?

Now the question does it is possible to select the Port Source & Port Destination for Through in Manual control ?
See following cases:
- Port1 => Through => Port3
- Port1 => Through => Port4
- Port2 => Through => Port3
- Port2 => Through => Port4
It can be interesting to use the eCal as a Switch or to calibrate manually 4 Ports VNA

**Comment by jankae** [comment]
> Now the question does it is possible to select the Port Source & Port Destination for Through in Manual control ?

Yes, just set the two ports you wish to connect both to the through standard. As long as only one port is set to through, no connection will be made.

> How does it is displayed with LEDs ?

While in manual mode: the LED of the selected port is blinking and if the port is currently set to a standard, the corresponding standard LED is on. 

While in normal operating mode (assuming a through connection between two ports and no other configured standards): through LED is on and the port LEDs of both ports as well. 

> Port1 => Through => Port3

1. set port 1 to through
2. Set port 3 to through

You can also have two through connections at the same time, as long as there is no overlap between the ports (e.g. 1<->3 and 2<->4). Throughs are connected in the order they are created. So for this example:

1. Set port 1 to through (no actual switching yet) 
2. Set port 3 to through (completes the connection between port 1 and 3)
3. Set port 2 to through (no actual switching yet) 
4. Set port 4 to through (completes the connection between port 2 and 4)

**Comment by bvernoux** [comment]
Thanks a lot for the clarification
