### ISSUE TITLE
Is it possible to make a duplicate firmware for LibreCal in case of replacing pe426462 with pe42482?

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreCAL#5]
Hi Jankae,
Judging by the layout of the printed circuit board, there will be physical changes only in the fact that in the case of the truth table Off, all switches will not be disabled, since V4 is connected to GND without reworking the board, and RFC needs to be switched to the RF1 output, which remains not connected anywhere.
The changes are as follows - instead of RF4 and RF6 in pe426462, you now need to switch RF6 and RF8 in pe42482, respectively. In the truth tables in the new version, it will look like this:

Connection P1V1 | P1V2 | P1V3 | P2V1 | P2V2 | P2V3 | P3V1 | P3V2 | P3V3 | P4V1 | P4V2 | P4V3
Through_12     0         1          0         1           0         1         X         X          X         X          X         X   
Through_13     1         0          1         X           X         X         0         0          1         X          X         X   
Through_14    0         0          1         X           X         X         X        X          X         0          0         1   
Through_23     X         X         X         0           1         0          0         1          0         X          X         X   
Through_24     X         X         X         0           0         1          X         X         X         1          0         1   
Through_34     X         X         X         X           X         X         1         0          1         0          1         0

Instead of RF4 (011) now RF6 (101).

Connection | V1 | V2 | V3 |        
Load               1     1     1  (instead of RF6 (101) now RF8 (111) )
Off                  0     0     0  (instead of disabling all switches (110) now switching RFC to RF1 (000) ).

Best regards.

**Comment by jankae** [comment]
It is technically possible but I believe it would cause more confusion than it would solve problems:
- There are no plans to produce a version with PE426482
- If there were two different versions, the user needs to flash the correct firmware update (the hardware is unable to determine whether a PE4264**6**2 or PE4264**8**2 is populated). If the user flashes the wrong firmware by mistake, some functions would not work properly

If you yourself are building a version with the PE4264**8**2, I suggest you fork the repository and do the changes yourself for your special version of the device. You won't even have to set up the toolchain, just pushing the changes in your fork should get you a compiled firmware.

**Comment by YuryW** [comment]
> I suggest you fork the repository and do the changes yourself for your special version of the device.

Hi Jankae, 
Thanks a lot for developing LibreVNA and LibreCal. But I don’t have enough knowledge yet to do it myself or work fully with github. The main thing is that you have confirmed that such a replacement is, in principle, possible. Not in vain wasted time on datasheets. Perhaps this will someday help someone in the case when they assemble the device themselves or for some reason replace the switch chips. We close the question.
Best wishes.
